version: "3.9"
services:
    mysql:
      image: mysql:8.0
      container_name: mysql-container
      restart: always
      environment:
        MYSQL_DATABASE: studio_beard
        MYSQL_ROOT_PASSWORD: root
        MYSQL_ROOT_HOST: 127.0.0.1
      ports:
        - '3306:3306'
      volumes:
        - mysql:/var/lib/mysql

volumes:
  mysql: